basePath: /api/v1
definitions:
  common.Result:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
  dto.LoginParams:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  dto.QueryUserListParams:
    properties:
      current:
        description: 当前页
        type: integer
      email:
        description: 邮箱
        type: string
      size:
        description: 页的大小
        type: integer
      status:
        description: '1：正常 2: 禁用'
        type: integer
      username:
        description: 用户名
        type: string
    type: object
  dto.RegisterParams:
    properties:
      email:
        type: string
      mobile:
        type: string
      password:
        maxLength: 32
        minLength: 6
        type: string
      roleIds:
        items:
          type: string
        type: array
      username:
        maxLength: 16
        minLength: 4
        type: string
    required:
    - email
    - mobile
    - password
    - roleIds
    - username
    type: object
host: 127.0.0.1:3000
info:
  contact: {}
  description: This is a sample Server pets
  title: Gin Project API
  version: 0.0.1
paths:
  /hello:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: 健康检查
      tags:
      - test
  /user/list:
    post:
      consumes:
      - application/json
      parameters:
      - description: 登录参数
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/dto.QueryUserListParams'
      produces:
      - application/json
      responses:
        "200":
          description: 成功返回体
          schema:
            $ref: '#/definitions/common.Result'
      summary: 用户列表
      tags:
      - 用户模块
  /user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 登录参数
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/dto.LoginParams'
      produces:
      - application/json
      responses:
        "200":
          description: 成功返回体
          schema:
            $ref: '#/definitions/common.Result'
      summary: 用户登录接口
      tags:
      - 用户模块
  /user/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 注册参数
        in: body
        name: params
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterParams'
      produces:
      - application/json
      responses:
        "200":
          description: 成功返回体
          schema:
            $ref: '#/definitions/common.Result'
      summary: 用户注册接口
      tags:
      - 用户模块
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
